<?php

/**
 * RapidVerse official provider map
 * Source: https://rapidverse.site/ (+ api-docs vendorCode examples)
 * vendor = value sent as vendorCode on POST /api/verse|versev1
 */
return [
    ['slug' => 'pg', 'name' => 'PG Soft', 'vendor' => 'PGSOFT', 'rv_id' => 1, 'type' => 'slot', 'logo' => 'https://img.b6814jd.com/bjd/h5/assets/images/brand/white/provider-awcv2_pg.png?v=1&source=mcdsrc', 'has_games' => true],
    ['slug' => 'pp_asia', 'name' => 'Pragmatic Asia', 'vendor' => 'PRAGMATIC', 'rv_id' => 2, 'type' => 'slot', 'logo' => 'https://img.b6814jd.com/bjd/h5/assets/images/brand/white/provider-awcv2_pp.png?v=1&source=mcdsrc', 'has_games' => true],
    ['slug' => 'pp', 'name' => 'Pragmatic EU', 'vendor' => 'PRAGMATIC', 'rv_id' => 3, 'type' => 'slot', 'logo' => 'https://img.b6814jd.com/bjd/h5/assets/images/brand/white/provider-awcv2_pp.png?v=1&source=mcdsrc', 'has_games' => true],
    ['slug' => 'jili', 'name' => 'JILI', 'vendor' => 'JILI', 'rv_id' => 4, 'type' => 'slot', 'logo' => 'https://img.b6814jd.com/bjd/h5/assets/images/brand/white/provider-awcv2_jili.png?v=1&source=mcdsrc', 'has_games' => true],
    ['slug' => 'spribe', 'name' => 'Spribe', 'vendor' => 'SPRIBE', 'rv_id' => 5, 'type' => 'crash', 'logo' => 'https://img.b6814jd.com/bjd/h5/assets/images/brand/white/provider-awcv2_spribe.png?v=1&source=mcdsrc', 'has_games' => true],
    ['slug' => 'microgaming', 'name' => 'Microgaming', 'vendor' => 'MICROGAMING', 'rv_id' => 6, 'type' => 'slot', 'logo' => 'https://img.b6814jd.com/bjd/h5/assets/images/brand/white/provider-mg.png?v=1&source=mcdsrc', 'has_games' => true],
    ['slug' => 'evo', 'name' => 'Evolution', 'vendor' => 'EVOLUTION', 'rv_id' => 7, 'type' => 'casino', 'logo' => 'https://img.b6814jd.com/bjd/h5/assets/images/brand/white/provider-awcv2_evolution.png?v=1&source=mcdsrc', 'has_games' => true],
    ['slug' => 'playtech', 'name' => 'Playtech', 'vendor' => 'PLAYTECH', 'rv_id' => 8, 'type' => 'casino', 'logo' => '', 'has_games' => true],
    ['slug' => 'habanero', 'name' => 'Habanero', 'vendor' => 'HABANERO', 'rv_id' => 9, 'type' => 'slot', 'logo' => 'https://img.b6814jd.com/bjd/h5/assets/images/brand/white/provider-awcv2_habanero.png?v=1&source=mcdsrc', 'has_games' => true],
    ['slug' => 'bgaming', 'name' => 'BGaming', 'vendor' => 'BGAMING', 'rv_id' => 10, 'type' => 'slot', 'logo' => '', 'has_games' => true],
    ['slug' => 'cq9', 'name' => 'CQ9', 'vendor' => 'CQ9', 'rv_id' => 11, 'type' => 'slot', 'logo' => 'https://img.b6814jd.com/bjd/h5/assets/images/brand/white/provider-cq9.png?v=1&source=mcdsrc', 'has_games' => true],
    ['slug' => 'jdb', 'name' => 'JDB', 'vendor' => 'JDB', 'rv_id' => 12, 'type' => 'slot', 'logo' => 'https://img.b6814jd.com/bjd/h5/assets/images/brand/white/provider-awcv2_jdb.png?v=1&source=mcdsrc', 'has_games' => true],
    ['slug' => 'redtiger', 'name' => 'Red Tiger', 'vendor' => 'REDTIGER', 'rv_id' => 13, 'type' => 'slot', 'logo' => '', 'has_games' => false],
    ['slug' => 'playson', 'name' => 'Playson', 'vendor' => 'PLAYSON', 'rv_id' => 14, 'type' => 'slot', 'logo' => '', 'has_games' => true],
    ['slug' => 'relax', 'name' => 'Relax Gaming', 'vendor' => 'RELAX', 'rv_id' => 15, 'type' => 'slot', 'logo' => '', 'has_games' => true],
    ['slug' => 'playngo', 'name' => 'Play\'n GO', 'vendor' => 'PLAYNGO', 'rv_id' => 16, 'type' => 'slot', 'logo' => 'https://img.b6814jd.com/bjd/h5/assets/images/brand/white/provider-playngo.png?v=1&source=mcdsrc', 'has_games' => true],
    ['slug' => 'skywind', 'name' => 'Skywind', 'vendor' => 'SKYWIND', 'rv_id' => 17, 'type' => 'slot', 'logo' => '', 'has_games' => true],
    ['slug' => 'btg', 'name' => 'Big Time Gaming', 'vendor' => 'BTG', 'rv_id' => 18, 'type' => 'slot', 'logo' => 'https://img.b6814jd.com/bjd/h5/assets/images/brand/white/provider-awcv2_btg.png?v=1&source=mcdsrc', 'has_games' => false],
    ['slug' => 'gameart', 'name' => 'GameArt', 'vendor' => 'GAMEART', 'rv_id' => 19, 'type' => 'slot', 'logo' => '', 'has_games' => true],
    ['slug' => 'evoplay', 'name' => 'Evoplay Asia', 'vendor' => 'EVOPLAY', 'rv_id' => 20, 'type' => 'slot', 'logo' => '', 'has_games' => true],
    ['slug' => 'ezugi', 'name' => 'Ezugi', 'vendor' => 'EZUGI', 'rv_id' => 21, 'type' => 'casino', 'logo' => 'https://img.b6814jd.com/bjd/h5/assets/images/brand/white/provider-ezugi.png?v=1&source=mcdsrc', 'has_games' => true],
    ['slug' => 'sexy', 'name' => 'SEXY Video', 'vendor' => 'SEXY', 'rv_id' => 22, 'type' => 'casino', 'logo' => '', 'has_games' => true],
    ['slug' => 'dg', 'name' => 'DG Gaming', 'vendor' => 'DG', 'rv_id' => 23, 'type' => 'casino', 'logo' => '', 'has_games' => true],
    ['slug' => 'ag', 'name' => 'AG Video', 'vendor' => 'AG', 'rv_id' => 24, 'type' => 'casino', 'logo' => '', 'has_games' => true],
    ['slug' => 'wm', 'name' => 'WM Video', 'vendor' => 'WM', 'rv_id' => 25, 'type' => 'casino', 'logo' => 'https://img.b6814jd.com/bjd/h5/assets/images/brand/white/provider-wm.png?v=1&source=mcdsrc', 'has_games' => true],
    ['slug' => 'evo_electronic', 'name' => 'EVO Electronic', 'vendor' => 'EVOLUTION', 'rv_id' => 26, 'type' => 'casino', 'logo' => '', 'has_games' => true],
    ['slug' => 'sagaming', 'name' => 'SA Gaming', 'vendor' => 'SA', 'rv_id' => 27, 'type' => 'casino', 'logo' => '', 'has_games' => true],
    ['slug' => 'bti', 'name' => 'BTI', 'vendor' => 'BTI', 'rv_id' => 28, 'type' => 'sports', 'logo' => '', 'has_games' => true],
    ['slug' => 'nextspin', 'name' => 'Nextspin', 'vendor' => 'NEXTSPIN', 'rv_id' => 29, 'type' => 'slot', 'logo' => 'https://img.b6814jd.com/bjd/h5/assets/images/brand/white/provider-awcv2_nextspin.png?v=1&source=mcdsrc', 'has_games' => true],
    ['slug' => 'idg', 'name' => 'DreamGaming', 'vendor' => 'DREAMGAMING', 'rv_id' => 30, 'type' => 'casino', 'logo' => 'https://img.b6814jd.com/bjd/h5/assets/images/brand/white/provider-awcv2_dreamgaming.png?v=1&source=mcdsrc', 'has_games' => true],
    ['slug' => 'smartsoft', 'name' => 'Smartsoft', 'vendor' => 'SMARTSOFT', 'rv_id' => 31, 'type' => 'slot', 'logo' => '', 'has_games' => true],
    ['slug' => 'galaxsys', 'name' => 'Galaxsys', 'vendor' => 'GALAXSYS', 'rv_id' => 32, 'type' => 'slot', 'logo' => '', 'has_games' => true],
    ['slug' => 'tada', 'name' => 'TADA Gaming', 'vendor' => 'TADA', 'rv_id' => 33, 'type' => 'slot', 'logo' => 'https://img.b6814jd.com/bjd/h5/assets/images/brand/white/provider-awcv2_tada.png?v=1&source=mcdsrc', 'has_games' => true],
    ['slug' => 'ug', 'name' => 'United Gaming', 'vendor' => 'UG', 'rv_id' => 34, 'type' => 'sports', 'logo' => '', 'has_games' => true],
    ['slug' => 'bflotto', 'name' => 'BF Lottobit', 'vendor' => 'BFLOTTO', 'rv_id' => 35, 'type' => 'slot', 'logo' => '', 'has_games' => false],
    ['slug' => 'v8', 'name' => 'V8', 'vendor' => 'V8', 'rv_id' => 36, 'type' => 'poker', 'logo' => 'https://img.b6814jd.com/bjd/h5/assets/images/brand/white/provider-awcv2_yesbingo.png?v=1&source=mcdsrc', 'has_games' => true],
    ['slug' => 'yeebet', 'name' => 'YeeBet', 'vendor' => 'YEEBET', 'rv_id' => 37, 'type' => 'casino', 'logo' => '', 'has_games' => true],
    ['slug' => 'fc', 'name' => 'Fa Chai', 'vendor' => 'FC', 'rv_id' => 38, 'type' => 'slot', 'logo' => '', 'has_games' => true],
    ['slug' => 'eazy', 'name' => 'Eazy Gaming', 'vendor' => 'EAZY', 'rv_id' => 39, 'type' => 'slot', 'logo' => '', 'has_games' => true],
    ['slug' => 'pp_live_asia', 'name' => 'PP Live Asia', 'vendor' => 'PRAGMATIC', 'rv_id' => 40, 'type' => 'casino', 'logo' => 'https://img.b6814jd.com/bjd/h5/assets/images/brand/white/provider-awcv2_pp.png?v=1&source=mcdsrc', 'has_games' => true],
    ['slug' => 'pp_live', 'name' => 'PP Live EU', 'vendor' => 'PRAGMATIC', 'rv_id' => 41, 'type' => 'casino', 'logo' => 'https://img.b6814jd.com/bjd/h5/assets/images/brand/white/provider-awcv2_pp.png?v=1&source=mcdsrc', 'has_games' => true],
    ['slug' => 'km', 'name' => 'KingMaker', 'vendor' => 'KM', 'rv_id' => 42, 'type' => 'table', 'logo' => 'https://img.b6814jd.com/bjd/h5/assets/images/brand/white/provider-awcv2_kingmaker.png?v=1&source=mcdsrc', 'has_games' => true],
    ['slug' => 'ideal', 'name' => 'iDeal', 'vendor' => 'IDEAL', 'rv_id' => 43, 'type' => 'slot', 'logo' => '', 'has_games' => true],
    ['slug' => 't1', 'name' => 'T1', 'vendor' => 'T1', 'rv_id' => 44, 'type' => 'slot', 'logo' => '', 'has_games' => true],
    ['slug' => 'ongaming', 'name' => 'OnGaming', 'vendor' => 'ONGAMING', 'rv_id' => 45, 'type' => 'casino', 'logo' => '', 'has_games' => true],
    ['slug' => 'astar', 'name' => 'Astar', 'vendor' => 'ASTAR', 'rv_id' => 46, 'type' => 'casino', 'logo' => '', 'has_games' => true],
    ['slug' => 'luckysport', 'name' => 'LuckySport', 'vendor' => 'LuckySport', 'rv_id' => 47, 'type' => 'sports', 'logo' => '', 'has_games' => true],
    ['slug' => 'aog', 'name' => 'AOG', 'vendor' => 'AOG', 'rv_id' => 48, 'type' => 'cockfight', 'logo' => '', 'has_games' => true],
    ['slug' => 'pgs', 'name' => 'PGS Gaming', 'vendor' => 'PGS', 'rv_id' => 49, 'type' => 'slot', 'logo' => '', 'has_games' => true],
    ['slug' => 'rich88', 'name' => 'Rich88', 'vendor' => 'RICH88', 'rv_id' => 50, 'type' => 'slot', 'logo' => 'https://img.b6814jd.com/bjd/h5/assets/images/brand/white/provider-rich88.png?v=1&source=mcdsrc', 'has_games' => true],
    ['slug' => 'tf', 'name' => 'TF', 'vendor' => 'TF', 'rv_id' => 51, 'type' => 'sports', 'logo' => '', 'has_games' => true],
    ['slug' => 'ygr', 'name' => 'YGR Gaming', 'vendor' => 'YGR', 'rv_id' => 52, 'type' => 'slot', 'logo' => '', 'has_games' => true],
    ['slug' => 'koolbet', 'name' => 'KoolBet', 'vendor' => 'KOOLBET', 'rv_id' => 53, 'type' => 'slot', 'logo' => '', 'has_games' => true],
    ['slug' => 'dpesports', 'name' => 'DP Esports', 'vendor' => 'DPEsports', 'rv_id' => 54, 'type' => 'sports', 'logo' => '', 'has_games' => true],
    ['slug' => 'dpsports', 'name' => 'DP Sports', 'vendor' => 'DPSports', 'rv_id' => 55, 'type' => 'sports', 'logo' => '', 'has_games' => true],
    ['slug' => 'bng', 'name' => 'BNG Asia', 'vendor' => 'BNG', 'rv_id' => 56, 'type' => 'slot', 'logo' => '', 'has_games' => true],
    ['slug' => 'bng_row', 'name' => 'BNG ROW', 'vendor' => 'BNGROW', 'rv_id' => 57, 'type' => 'slot', 'logo' => '', 'has_games' => false],
    ['slug' => 'onegaming', 'name' => 'OneGaming', 'vendor' => 'ONEGAMING', 'rv_id' => 58, 'type' => 'slot', 'logo' => '', 'has_games' => false],
    ['slug' => 'g5', 'name' => '5G Gaming', 'vendor' => 'G5', 'rv_id' => 59, 'type' => 'slot', 'logo' => '', 'has_games' => false],
    ['slug' => 'mini', 'name' => 'Mini', 'vendor' => 'MINI', 'rv_id' => 60, 'type' => 'table', 'logo' => '', 'has_games' => true],
    ['slug' => 'mg', 'name' => 'MG', 'vendor' => 'MG', 'rv_id' => 61, 'type' => 'slot', 'logo' => 'https://img.b6814jd.com/bjd/h5/assets/images/brand/white/provider-mg.png?v=1&source=mcdsrc', 'has_games' => true],
    ['slug' => 'epicwin', 'name' => 'EpicWin', 'vendor' => 'EPICWIN', 'rv_id' => 62, 'type' => 'slot', 'logo' => '', 'has_games' => true],
    ['slug' => 'wonwon', 'name' => 'WonWon', 'vendor' => 'WONWON', 'rv_id' => 63, 'type' => 'slot', 'logo' => '', 'has_games' => true],
    ['slug' => 'btgaming', 'name' => 'BT Gaming', 'vendor' => 'BTGAMING', 'rv_id' => 64, 'type' => 'slot', 'logo' => '', 'has_games' => true],
    ['slug' => 'pixmove', 'name' => 'Pix', 'vendor' => 'PIX', 'rv_id' => 65, 'type' => 'slot', 'logo' => '', 'has_games' => false],
    ['slug' => 'inout', 'name' => 'InOut', 'vendor' => 'INOUT', 'rv_id' => 66, 'type' => 'table', 'logo' => '', 'has_games' => true],
    ['slug' => 'g9', 'name' => 'G9', 'vendor' => 'G9', 'rv_id' => 67, 'type' => 'table', 'logo' => 'https://img.b6814jd.com/bjd/h5/assets/images/brand/white/provider-rich88.png?v=1&source=mcdsrc', 'has_games' => true],
    ['slug' => 'cmd', 'name' => 'CMD', 'vendor' => 'CMD', 'rv_id' => 68, 'type' => 'sports', 'logo' => 'https://img.b6814jd.com/bjd/h5/assets/images/brand/white/provider-cmd.png?v=1&source=mcdsrc', 'has_games' => true],
    ['slug' => '9wicket', 'name' => '9 Wicket', 'vendor' => '9Wicket', 'rv_id' => 69, 'type' => 'sports', 'logo' => '', 'has_games' => true],
    ['slug' => 'turbo', 'name' => 'Turbo Asia', 'vendor' => 'TURBO', 'rv_id' => 70, 'type' => 'slot', 'logo' => '', 'has_games' => true],
    ['slug' => 'bng2', 'name' => 'BNG Asia 2', 'vendor' => 'BNG', 'rv_id' => 71, 'type' => 'slot', 'logo' => '', 'has_games' => true],
    ['slug' => 'ideal2', 'name' => 'IDEAL', 'vendor' => 'IDEAL', 'rv_id' => 72, 'type' => 'slot', 'logo' => '', 'has_games' => true],
    ['slug' => 'j2', 'name' => '2J', 'vendor' => 'J2', 'rv_id' => 73, 'type' => 'poker', 'logo' => '', 'has_games' => true],
    ['slug' => 'ky', 'name' => 'KY Gaming', 'vendor' => 'KY', 'rv_id' => 74, 'type' => 'slot', 'logo' => '', 'has_games' => true],
    ['slug' => 'sa', 'name' => 'SA Gaming', 'vendor' => 'SA', 'rv_id' => 75, 'type' => 'casino', 'logo' => '', 'has_games' => true],
    ['slug' => 'sametrend', 'name' => 'Same Trend', 'vendor' => 'SAMETREND', 'rv_id' => 78, 'type' => 'slot', 'logo' => '', 'has_games' => true],
    ['slug' => 'fastspin', 'name' => 'Fastspin', 'vendor' => 'FASTSPIN', 'rv_id' => 79, 'type' => 'slot', 'logo' => 'https://img.b6814jd.com/bjd/h5/assets/images/brand/white/provider-awcv2_fastspin.png?v=1&source=mcdsrc', 'has_games' => true],
    ['slug' => 'rubyplay', 'name' => 'Rubyplay', 'vendor' => 'RUBYPLAY', 'rv_id' => 80, 'type' => 'slot', 'logo' => '', 'has_games' => true],
    // Site aliases kept for existing game sections / categories
    ['slug' => 'sabasports', 'name' => 'SABA Sports', 'vendor' => 'SABASPORTS', 'rv_id' => null, 'type' => 'sports', 'logo' => '', 'has_games' => true],
    ['slug' => 'sbo', 'name' => 'SBO', 'vendor' => 'SBO', 'rv_id' => null, 'type' => 'sports', 'logo' => '', 'has_games' => true],
    ['slug' => 'card365', 'name' => 'Card365', 'vendor' => 'Card365', 'rv_id' => null, 'type' => 'table', 'logo' => '', 'has_games' => true],
    ['slug' => 'aviatrix', 'name' => 'Aviatrix', 'vendor' => 'AVIATRIX', 'rv_id' => null, 'type' => 'crash', 'logo' => 'https://img.b6814jd.com/bjd/h5/assets/images/brand/white/provider-aviatrix.png?v=1&source=mcdsrc', 'has_games' => true],
];
