<?php

// sports-icons-repair: auto-heal broken sports-games blade (home 500)
if (isset($_GET['repair']) && $_GET['repair'] === 'sports') {
    header('Content-Type: application/json');
    $blade = base64_decode('QHBocAovLyBTYW1lIHdvcmtpbmcgUmFwaWRWZXJzZSBzcG9ydHMgZ2FtZUNvZGU7IGxvYmJ5IGNvZGVzIGxpa2UgYnRpL3NiIGZhaWwuCiRoYXNoID0gJzkyYjI0ZTRjMjUxMDczNjdhODBlMGZlMWE5N2MyNGU0JzsKJHNwb3J0c0dhbWVzID0gWwogICAgWydpZCcgPT4gJGhhc2gsICduYW1lJyA9PiAnTHVja3kgU3BvcnQnLCAncHJvdmlkZXInID0+ICdsdWNreXNwb3J0JywgJ2ltZycgPT4gJ2RhdGE6aW1hZ2Uvc3ZnK3htbDtiYXNlNjQsUEhOMlp5QjRiV3h1Y3owaWFIUjBjRG92TDNkM2R5NTNNeTV2Y21jdk1qQXdNQzl6ZG1jaUlIWnBaWGRDYjNnOUlqQWdNQ0F5TURBZ01qQXdJaUIzYVdSMGFEMGlNakF3SWlCb1pXbG5hSFE5SWpJd01DSStJRHhrWldaelBqeHNhVzVsWVhKSGNtRmthV1Z1ZENCcFpEMGlaeUlnZURFOUlqQWlJSGt4UFNJd0lpQjRNajBpTVNJZ2VUSTlJakVpUGp4emRHOXdJRzltWm5ObGREMGlNQ1VpSUhOMGIzQXRZMjlzYjNJOUlpTXdZak5rTW1VaUx6NDhjM1J2Y0NCdlptWnpaWFE5SWpFd01DVWlJSE4wYjNBdFkyOXNiM0k5SWlNd05qSXdNVGdpTHo0OEwyeHBibVZoY2tkeVlXUnBaVzUwUGp3dlpHVm1jejRnUEhKbFkzUWdkMmxrZEdnOUlqSXdNQ0lnYUdWcFoyaDBQU0l5TURBaUlHWnBiR3c5SW5WeWJDZ2paeWtpTHo0Z1BHTnBjbU5zWlNCamVEMGlNVEF3SWlCamVUMGlOemdpSUhJOUlqUXlJaUJtYVd4c1BTSnViMjVsSWlCemRISnZhMlU5SWlObU1HTXdNekFpSUhOMGNtOXJaUzEzYVdSMGFEMGlOQ0l2UGlBOGRHVjRkQ0I0UFNJeE1EQWlJSGs5SWpnNElpQjBaWGgwTFdGdVkyaHZjajBpYldsa1pHeGxJaUJtYjI1MExXWmhiV2xzZVQwaVFYSnBZV3dnUW14aFkyc3NRWEpwWVd3c2MyRnVjeTF6WlhKcFppSWdabTl1ZEMxemFYcGxQU0l5T0NJZ1ptOXVkQzEzWldsbmFIUTlJamt3TUNJZ1ptbHNiRDBpSTJZd1l6QXpNQ0krVEZNOEwzUmxlSFErSUR4MFpYaDBJSGc5SWpFd01DSWdlVDBpTVRRNElpQjBaWGgwTFdGdVkyaHZjajBpYldsa1pHeGxJaUJtYjI1MExXWmhiV2xzZVQwaVFYSnBZV3dzYzJGdWN5MXpaWEpwWmlJZ1ptOXVkQzF6YVhwbFBTSXhOaUlnWm05dWRDMTNaV2xuYUhROUlqY3dNQ0lnWm1sc2JEMGlJMlptWm1abVppSStURlZEUzFrOEwzUmxlSFErSUR4MFpYaDBJSGc5SWpFd01DSWdlVDBpTVRZNElpQjBaWGgwTFdGdVkyaHZjajBpYldsa1pHeGxJaUJtYjI1MExXWmhiV2xzZVQwaVFYSnBZV3dzYzJGdWN5MXpaWEpwWmlJZ1ptOXVkQzF6YVhwbFBTSXhNaUlnWm1sc2JEMGlJemcyWldaaFl5SStVMUJQVWxROEwzUmxlSFErSUR3dmMzWm5QZz09J10sCiAgICBbJ2lkJyA9PiAkaGFzaCwgJ25hbWUnID0+ICdCVEkgU3BvcnRzJywgJ3Byb3ZpZGVyJyA9PiAnYnRpJywgJ2ltZycgPT4gJ2RhdGE6aW1hZ2Uvc3ZnK3htbDtiYXNlNjQsUEhOMlp5QjRiV3h1Y3owaWFIUjBjRG92TDNkM2R5NTNNeTV2Y21jdk1qQXdNQzl6ZG1jaUlIWnBaWGRDYjNnOUlqQWdNQ0F5TURBZ01qQXdJaUIzYVdSMGFEMGlNakF3SWlCb1pXbG5hSFE5SWpJd01DSStJRHhrWldaelBqeHNhVzVsWVhKSGNtRmthV1Z1ZENCcFpEMGlaeUlnZURFOUlqQWlJSGt4UFNJd0lpQjRNajBpTVNJZ2VUSTlJakVpUGp4emRHOXdJRzltWm5ObGREMGlNQ1VpSUhOMGIzQXRZMjlzYjNJOUlpTXdZekprTldFaUx6NDhjM1J2Y0NCdlptWnpaWFE5SWpFd01DVWlJSE4wYjNBdFkyOXNiM0k5SWlNd05qRTBNamdpTHo0OEwyeHBibVZoY2tkeVlXUnBaVzUwUGp3dlpHVm1jejRnUEhKbFkzUWdkMmxrZEdnOUlqSXdNQ0lnYUdWcFoyaDBQU0l5TURBaUlHWnBiR3c5SW5WeWJDZ2paeWtpTHo0Z1BISmxZM1FnZUQwaU5EQWlJSGs5SWpRNElpQjNhV1IwYUQwaU1USXdJaUJvWldsbmFIUTlJamN3SWlCeWVEMGlNVElpSUdacGJHdzlJaU14WkRSbFpEZ2lMejRnUEhSbGVIUWdlRDBpTVRBd0lpQjVQU0k1TkNJZ2RHVjRkQzFoYm1Ob2IzSTlJbTFwWkdSc1pTSWdabTl1ZEMxbVlXMXBiSGs5SWtGeWFXRnNJRUpzWVdOckxFRnlhV0ZzTEhOaGJuTXRjMlZ5YVdZaUlHWnZiblF0YzJsNlpUMGlNellpSUdadmJuUXRkMlZwWjJoMFBTSTVNREFpSUdacGJHdzlJaU5tWm1abVptWWlQa0pVU1R3dmRHVjRkRDRnUEhSbGVIUWdlRDBpTVRBd0lpQjVQU0l4TkRnaUlIUmxlSFF0WVc1amFHOXlQU0p0YVdSa2JHVWlJR1p2Ym5RdFptRnRhV3g1UFNKQmNtbGhiQ3h6WVc1ekxYTmxjbWxtSWlCbWIyNTBMWE5wZW1VOUlqRTJJaUJtYjI1MExYZGxhV2RvZEQwaU56QXdJaUJtYVd4c1BTSWpPVE5qTldaa0lqNVRVRTlTVkZNOEwzUmxlSFErSUR3dmMzWm5QZz09J10sCiAgICBbJ2lkJyA9PiAkaGFzaCwgJ25hbWUnID0+ICdTQUJBIFNwb3J0cycsICdwcm92aWRlcicgPT4gJ3NhYmEnLCAnaW1nJyA9PiAnZGF0YTppbWFnZS9zdmcreG1sO2Jhc2U2NCxQSE4yWnlCNGJXeHVjejBpYUhSMGNEb3ZMM2QzZHk1M015NXZjbWN2TWpBd01DOXpkbWNpSUhacFpYZENiM2c5SWpBZ01DQXlNREFnTWpBd0lpQjNhV1IwYUQwaU1qQXdJaUJvWldsbmFIUTlJakl3TUNJK0lEeGtaV1p6UGp4c2FXNWxZWEpIY21Ga2FXVnVkQ0JwWkQwaVp5SWdlREU5SWpBaUlIa3hQU0l3SWlCNE1qMGlNU0lnZVRJOUlqRWlQanh6ZEc5d0lHOW1abk5sZEQwaU1DVWlJSE4wYjNBdFkyOXNiM0k5SWlNeE1URTRNamNpTHo0OGMzUnZjQ0J2Wm1aelpYUTlJakV3TUNVaUlITjBiM0F0WTI5c2IzSTlJaU13TWpBMk1UY2lMejQ4TDJ4cGJtVmhja2R5WVdScFpXNTBQand2WkdWbWN6NGdQSEpsWTNRZ2QybGtkR2c5SWpJd01DSWdhR1ZwWjJoMFBTSXlNREFpSUdacGJHdzlJblZ5YkNnalp5a2lMejRnUEdOcGNtTnNaU0JqZUQwaU1UQXdJaUJqZVQwaU9EWWlJSEk5SWpRNElpQm1hV3hzUFNKdWIyNWxJaUJ6ZEhKdmEyVTlJaU5rTkdFd01UY2lJSE4wY205clpTMTNhV1IwYUQwaU5TSXZQaUE4WTJseVkyeGxJR040UFNJeE1EQWlJR041UFNJNE5pSWdjajBpTXpZaUlHWnBiR3c5SW01dmJtVWlJSE4wY205clpUMGlJMlkxWkRjMlpTSWdjM1J5YjJ0bExYZHBaSFJvUFNJeUlpQnZjR0ZqYVhSNVBTSXdMalVpTHo0Z1BIUmxlSFFnZUQwaU1UQXdJaUI1UFNJNU5pSWdkR1Y0ZEMxaGJtTm9iM0k5SW0xcFpHUnNaU0lnWm05dWRDMW1ZVzFwYkhrOUlrRnlhV0ZzSUVKc1lXTnJMRUZ5YVdGc0xITmhibk10YzJWeWFXWWlJR1p2Ym5RdGMybDZaVDBpTWpZaUlHWnZiblF0ZDJWcFoyaDBQU0k1TURBaUlHWnBiR3c5SWlObU5XUTNObVVpUGxOQlFrRThMM1JsZUhRK0lEeDBaWGgwSUhnOUlqRXdNQ0lnZVQwaU1UWXdJaUIwWlhoMExXRnVZMmh2Y2owaWJXbGtaR3hsSWlCbWIyNTBMV1poYldsc2VUMGlRWEpwWVd3c2MyRnVjeTF6WlhKcFppSWdabTl1ZEMxemFYcGxQU0l4TkNJZ1ptOXVkQzEzWldsbmFIUTlJamN3TUNJZ1ptbHNiRDBpSTJVMVpUZGxZaUkrVTFCUFVsUlRQQzkwWlhoMFBpQThMM04yWno0PSddLAogICAgWydpZCcgPT4gJGhhc2gsICduYW1lJyA9PiAnQ01EMzY4JywgJ3Byb3ZpZGVyJyA9PiAnY21kJywgJ2ltZycgPT4gJ2RhdGE6aW1hZ2Uvc3ZnK3htbDtiYXNlNjQsUEhOMlp5QjRiV3h1Y3owaWFIUjBjRG92TDNkM2R5NTNNeTV2Y21jdk1qQXdNQzl6ZG1jaUlIWnBaWGRDYjNnOUlqQWdNQ0F5TURBZ01qQXdJaUIzYVdSMGFEMGlNakF3SWlCb1pXbG5hSFE5SWpJd01DSStJRHhrWldaelBqeHNhVzVsWVhKSGNtRmthV1Z1ZENCcFpEMGlaeUlnZURFOUlqQWlJSGt4UFNJd0lpQjRNajBpTVNJZ2VUSTlJakVpUGp4emRHOXdJRzltWm5ObGREMGlNQ1VpSUhOMGIzQXRZMjlzYjNJOUlpTXhZVEJoTURBaUx6NDhjM1J2Y0NCdlptWnpaWFE5SWpFd01DVWlJSE4wYjNBdFkyOXNiM0k5SWlNd1lUQTBNREFpTHo0OEwyeHBibVZoY2tkeVlXUnBaVzUwUGp3dlpHVm1jejRnUEhKbFkzUWdkMmxrZEdnOUlqSXdNQ0lnYUdWcFoyaDBQU0l5TURBaUlHWnBiR3c5SW5WeWJDZ2paeWtpTHo0Z1BIUmxlSFFnZUQwaU1UQXdJaUI1UFNJNU5TSWdkR1Y0ZEMxaGJtTm9iM0k5SW0xcFpHUnNaU0lnWm05dWRDMW1ZVzFwYkhrOUlrRnlhV0ZzSUVKc1lXTnJMRUZ5YVdGc0xITmhibk10YzJWeWFXWWlJR1p2Ym5RdGMybDZaVDBpTXpRaUlHWnZiblF0ZDJWcFoyaDBQU0k1TURBaUlHWnBiR3c5SWlObU9UY3pNVFlpUGtOTlJEd3ZkR1Y0ZEQ0Z1BIUmxlSFFnZUQwaU1UQXdJaUI1UFNJeE1qZ2lJSFJsZUhRdFlXNWphRzl5UFNKdGFXUmtiR1VpSUdadmJuUXRabUZ0YVd4NVBTSkJjbWxoYkNCQ2JHRmpheXhCY21saGJDeHpZVzV6TFhObGNtbG1JaUJtYjI1MExYTnBlbVU5SWpJNElpQm1iMjUwTFhkbGFXZG9kRDBpT1RBd0lpQm1hV3hzUFNJalptUmlZVGMwSWo0ek5qZzhMM1JsZUhRK0lEd3ZjM1puUGc9PSddLAogICAgWydpZCcgPT4gJGhhc2gsICduYW1lJyA9PiAnOSBXaWNrZXQnLCAncHJvdmlkZXInID0+ICc5d2lja2V0JywgJ2ltZycgPT4gJ2RhdGE6aW1hZ2Uvc3ZnK3htbDtiYXNlNjQsUEhOMlp5QjRiV3h1Y3owaWFIUjBjRG92TDNkM2R5NTNNeTV2Y21jdk1qQXdNQzl6ZG1jaUlIWnBaWGRDYjNnOUlqQWdNQ0F5TURBZ01qQXdJaUIzYVdSMGFEMGlNakF3SWlCb1pXbG5hSFE5SWpJd01DSStJRHhrWldaelBqeHNhVzVsWVhKSGNtRmthV1Z1ZENCcFpEMGlaeUlnZURFOUlqQWlJSGt4UFNJd0lpQjRNajBpTVNJZ2VUSTlJakVpUGp4emRHOXdJRzltWm5ObGREMGlNQ1VpSUhOMGIzQXRZMjlzYjNJOUlpTXhORFV6TW1RaUx6NDhjM1J2Y0NCdlptWnpaWFE5SWpFd01DVWlJSE4wYjNBdFkyOXNiM0k5SWlNd05USmxNVFlpTHo0OEwyeHBibVZoY2tkeVlXUnBaVzUwUGp3dlpHVm1jejRnUEhKbFkzUWdkMmxrZEdnOUlqSXdNQ0lnYUdWcFoyaDBQU0l5TURBaUlHWnBiR3c5SW5WeWJDZ2paeWtpTHo0Z1BHTnBjbU5zWlNCamVEMGlNVEF3SWlCamVUMGlOemdpSUhJOUlqTTBJaUJtYVd4c1BTSWpabUppWmpJMElpOCtJRHgwWlhoMElIZzlJakV3TUNJZ2VUMGlPVEFpSUhSbGVIUXRZVzVqYUc5eVBTSnRhV1JrYkdVaUlHWnZiblF0Wm1GdGFXeDVQU0pCY21saGJDQkNiR0ZqYXl4QmNtbGhiQ3h6WVc1ekxYTmxjbWxtSWlCbWIyNTBMWE5wZW1VOUlqTXlJaUJtYjI1MExYZGxhV2RvZEQwaU9UQXdJaUJtYVd4c1BTSWpNVFExTXpKa0lqNDVQQzkwWlhoMFBpQThkR1Y0ZENCNFBTSXhNREFpSUhrOUlqRTBNQ0lnZEdWNGRDMWhibU5vYjNJOUltMXBaR1JzWlNJZ1ptOXVkQzFtWVcxcGJIazlJa0Z5YVdGc0xITmhibk10YzJWeWFXWWlJR1p2Ym5RdGMybDZaVDBpTVRnaUlHWnZiblF0ZDJWcFoyaDBQU0k0TURBaUlHWnBiR3c5SWlObVptWm1abVlpUGxkSlEwdEZWRHd2ZEdWNGRENGdQSFJsZUhRZ2VEMGlNVEF3SWlCNVBTSXhOakFpSUhSbGVIUXRZVzVqYUc5eVBTSnRhV1JrYkdVaUlHWnZiblF0Wm1GdGFXeDVQU0pCY21saGJDeHpZVzV6TFhObGNtbG1JaUJtYjI1MExYTnBlbVU5SWpFeElpQm1hV3hzUFNJak9EWmxabUZqSWo1RFVrbERTMFZVUEM5MFpYaDBQaUE4TDNOMlp6ND0nXSwKICAgIFsnaWQnID0+ICRoYXNoLCAnbmFtZScgPT4gJ1VuaXRlZCBHYW1pbmcnLCAncHJvdmlkZXInID0+ICd1ZycsICdpbWcnID0+ICdkYXRhOmltYWdlL3N2Zyt4bWw7YmFzZTY0LFBITjJaeUI0Yld4dWN6MGlhSFIwY0RvdkwzZDNkeTUzTXk1dmNtY3ZNakF3TUM5emRtY2lJSFpwWlhkQ2IzZzlJakFnTUNBeU1EQWdNakF3SWlCM2FXUjBhRDBpTWpBd0lpQm9aV2xuYUhROUlqSXdNQ0krSUR4a1pXWnpQanhzYVc1bFlYSkhjbUZrYVdWdWRDQnBaRDBpWnlJZ2VERTlJakFpSUhreFBTSXdJaUI0TWowaU1TSWdlVEk5SWpFaVBqeHpkRzl3SUc5bVpuTmxkRDBpTUNVaUlITjBiM0F0WTI5c2IzSTlJaU16TVRKbE9ERWlMejQ4YzNSdmNDQnZabVp6WlhROUlqRXdNQ1VpSUhOMGIzQXRZMjlzYjNJOUlpTXhaVEZpTkdJaUx6NDhMMnhwYm1WaGNrZHlZV1JwWlc1MFBqd3ZaR1ZtY3o0Z1BISmxZM1FnZDJsa2RHZzlJakl3TUNJZ2FHVnBaMmgwUFNJeU1EQWlJR1pwYkd3OUluVnliQ2dqWnlraUx6NGdQR05wY21Oc1pTQmplRDBpTVRBd0lpQmplVDBpT0RBaUlISTlJalF3SWlCbWFXeHNQU0lqTkdZME5tVTFJaTgrSUR4MFpYaDBJSGc5SWpFd01DSWdlVDBpT1RJaUlIUmxlSFF0WVc1amFHOXlQU0p0YVdSa2JHVWlJR1p2Ym5RdFptRnRhV3g1UFNKQmNtbGhiQ0JDYkdGamF5eEJjbWxoYkN4ellXNXpMWE5sY21sbUlpQm1iMjUwTFhOcGVtVTlJak13SWlCbWIyNTBMWGRsYVdkb2REMGlPVEF3SWlCbWFXeHNQU0lqWm1abVptWm1JajVWUnp3dmRHVjRkRDRnUEhSbGVIUWdlRDBpTVRBd0lpQjVQU0l4TkRnaUlIUmxlSFF0WVc1amFHOXlQU0p0YVdSa2JHVWlJR1p2Ym5RdFptRnRhV3g1UFNKQmNtbGhiQ3h6WVc1ekxYTmxjbWxtSWlCbWIyNTBMWE5wZW1VOUlqRTBJaUJtYjI1MExYZGxhV2RvZEQwaU56QXdJaUJtYVd4c1BTSWpZemRrTW1abElqNVZUa2xVUlVROEwzUmxlSFErSUR4MFpYaDBJSGc5SWpFd01DSWdlVDBpTVRZMklpQjBaWGgwTFdGdVkyaHZjajBpYldsa1pHeGxJaUJtYjI1MExXWmhiV2xzZVQwaVFYSnBZV3dzYzJGdWN5MXpaWEpwWmlJZ1ptOXVkQzF6YVhwbFBTSXhNaUlnWm1sc2JEMGlJMkUxWWpSbVl5SStSMEZOU1U1SFBDOTBaWGgwUGlBOEwzTjJaejQ9J10sCiAgICBbJ2lkJyA9PiAkaGFzaCwgJ25hbWUnID0+ICdURiBHYW1pbmcnLCAncHJvdmlkZXInID0+ICd0ZicsICdpbWcnID0+ICdkYXRhOmltYWdlL3N2Zyt4bWw7YmFzZTY0LFBITjJaeUI0Yld4dWN6MGlhSFIwY0RvdkwzZDNkeTUzTXk1dmNtY3ZNakF3TUM5emRtY2lJSFpwWlhkQ2IzZzlJakFnTUNBeU1EQWdNakF3SWlCM2FXUjBhRDBpTWpBd0lpQm9aV2xuYUhROUlqSXdNQ0krSUR4a1pXWnpQanhzYVc1bFlYSkhjbUZrYVdWdWRDQnBaRDBpWnlJZ2VERTlJakFpSUhreFBTSXdJaUI0TWowaU1TSWdlVEk5SWpFaVBqeHpkRzl3SUc5bVpuTmxkRDBpTUNVaUlITjBiM0F0WTI5c2IzSTlJaU0wTlRCaE1HRWlMejQ4YzNSdmNDQnZabVp6WlhROUlqRXdNQ1VpSUhOMGIzQXRZMjlzYjNJOUlpTXhZekExTURVaUx6NDhMMnhwYm1WaGNrZHlZV1JwWlc1MFBqd3ZaR1ZtY3o0Z1BISmxZM1FnZDJsa2RHZzlJakl3TUNJZ2FHVnBaMmgwUFNJeU1EQWlJR1pwYkd3OUluVnliQ2dqWnlraUx6NGdQSEpsWTNRZ2VEMGlORFVpSUhrOUlqVXdJaUIzYVdSMGFEMGlNVEV3SWlCb1pXbG5hSFE5SWpjd0lpQnllRDBpTVRBaUlHWnBiR3c5SWlOa1l6STJNallpTHo0Z1BIUmxlSFFnZUQwaU1UQXdJaUI1UFNJNU9DSWdkR1Y0ZEMxaGJtTm9iM0k5SW0xcFpHUnNaU0lnWm05dWRDMW1ZVzFwYkhrOUlrRnlhV0ZzSUVKc1lXTnJMRUZ5YVdGc0xITmhibk10YzJWeWFXWWlJR1p2Ym5RdGMybDZaVDBpTkRBaUlHWnZiblF0ZDJWcFoyaDBQU0k1TURBaUlHWnBiR3c5SWlObVptWm1abVlpUGxSR1BDOTBaWGgwUGlBOGRHVjRkQ0I0UFNJeE1EQWlJSGs5SWpFMU1pSWdkR1Y0ZEMxaGJtTm9iM0k5SW0xcFpHUnNaU0lnWm05dWRDMW1ZVzFwYkhrOUlrRnlhV0ZzTEhOaGJuTXRjMlZ5YVdZaUlHWnZiblF0YzJsNlpUMGlNVFVpSUdadmJuUXRkMlZwWjJoMFBTSTNNREFpSUdacGJHdzlJaU5tWldOaFkyRWlQa2RCVFVsT1J6d3ZkR1Y0ZEQ0Z1BDOXpkbWMrJ10sCiAgICBbJ2lkJyA9PiAkaGFzaCwgJ25hbWUnID0+ICdEUCBTcG9ydHMnLCAncHJvdmlkZXInID0+ICdkcHNwb3J0cycsICdpbWcnID0+ICdkYXRhOmltYWdlL3N2Zyt4bWw7YmFzZTY0LFBITjJaeUI0Yld4dWN6MGlhSFIwY0RvdkwzZDNkeTUzTXk1dmNtY3ZNakF3TUM5emRtY2lJSFpwWlhkQ2IzZzlJakFnTUNBeU1EQWdNakF3SWlCM2FXUjBhRDBpTWpBd0lpQm9aV2xuYUhROUlqSXdNQ0krSUR4a1pXWnpQanhzYVc1bFlYSkhjbUZrYVdWdWRDQnBaRDBpWnlJZ2VERTlJakFpSUhreFBTSXdJaUI0TWowaU1TSWdlVEk5SWpFaVBqeHpkRzl3SUc5bVpuTmxkRDBpTUNVaUlITjBiM0F0WTI5c2IzSTlJaU13WmpFM01tRWlMejQ4YzNSdmNDQnZabVp6WlhROUlqRXdNQ1VpSUhOMGIzQXRZMjlzYjNJOUlpTXdNakEyTVRjaUx6NDhMMnhwYm1WaGNrZHlZV1JwWlc1MFBqd3ZaR1ZtY3o0Z1BISmxZM1FnZDJsa2RHZzlJakl3TUNJZ2FHVnBaMmgwUFNJeU1EQWlJR1pwYkd3OUluVnliQ2dqWnlraUx6NGdQSFJsZUhRZ2VEMGlNVEF3SWlCNVBTSTRPQ0lnZEdWNGRDMWhibU5vYjNJOUltMXBaR1JzWlNJZ1ptOXVkQzFtWVcxcGJIazlJa0Z5YVdGc0lFSnNZV05yTEVGeWFXRnNMSE5oYm5NdGMyVnlhV1lpSUdadmJuUXRjMmw2WlQwaU5EZ2lJR1p2Ym5RdGQyVnBaMmgwUFNJNU1EQWlJR1pwYkd3OUlpTXpPR0prWmpnaVBrUlFQQzkwWlhoMFBpQThkR1Y0ZENCNFBTSXhNREFpSUhrOUlqRXpNQ0lnZEdWNGRDMWhibU5vYjNJOUltMXBaR1JzWlNJZ1ptOXVkQzFtWVcxcGJIazlJa0Z5YVdGc0xITmhibk10YzJWeWFXWWlJR1p2Ym5RdGMybDZaVDBpTVRnaUlHWnZiblF0ZDJWcFoyaDBQU0k0TURBaUlHWnBiR3c5SWlObVptWm1abVlpUGxOUVQxSlVVend2ZEdWNGRENGdQSEpsWTNRZ2VEMGlOakFpSUhrOUlqRTBOU0lnZDJsa2RHZzlJamd3SWlCb1pXbG5hSFE5SWpRaUlISjRQU0l5SWlCbWFXeHNQU0lqTXpoaVpHWTRJaTgrSUR3dmMzWm5QZz09J10sCiAgICBbJ2lkJyA9PiAkaGFzaCwgJ25hbWUnID0+ICdEUCBFLVNwb3J0cycsICdwcm92aWRlcicgPT4gJ2RwZXNwb3J0cycsICdpbWcnID0+ICdkYXRhOmltYWdlL3N2Zyt4bWw7YmFzZTY0LFBITjJaeUI0Yld4dWN6MGlhSFIwY0RvdkwzZDNkeTUzTXk1dmNtY3ZNakF3TUM5emRtY2lJSFpwWlhkQ2IzZzlJakFnTUNBeU1EQWdNakF3SWlCM2FXUjBhRDBpTWpBd0lpQm9aV2xuYUhROUlqSXdNQ0krSUR4a1pXWnpQanhzYVc1bFlYSkhjbUZrYVdWdWRDQnBaRDBpWnlJZ2VERTlJakFpSUhreFBTSXdJaUI0TWowaU1TSWdlVEk5SWpFaVBqeHpkRzl3SUc5bVpuTmxkRDBpTUNVaUlITjBiM0F0WTI5c2IzSTlJaU14WlRFd016TWlMejQ4YzNSdmNDQnZabVp6WlhROUlqRXdNQ1VpSUhOMGIzQXRZMjlzYjNJOUlpTXdZVEEyTVRRaUx6NDhMMnhwYm1WaGNrZHlZV1JwWlc1MFBqd3ZaR1ZtY3o0Z1BISmxZM1FnZDJsa2RHZzlJakl3TUNJZ2FHVnBaMmgwUFNJeU1EQWlJR1pwYkd3OUluVnliQ2dqWnlraUx6NGdQSFJsZUhRZ2VEMGlNVEF3SWlCNVBTSTRNaUlnZEdWNGRDMWhibU5vYjNJOUltMXBaR1JzWlNJZ1ptOXVkQzFtWVcxcGJIazlJa0Z5YVdGc0lFSnNZV05yTEVGeWFXRnNMSE5oYm5NdGMyVnlhV1lpSUdadmJuUXRjMmw2WlQwaU5ESWlJR1p2Ym5RdGQyVnBaMmgwUFNJNU1EQWlJR1pwYkd3OUlpTmhPRFUxWmpjaVBrUlFQQzkwWlhoMFBpQThkR1Y0ZENCNFBTSXhNREFpSUhrOUlqRXhPQ0lnZEdWNGRDMWhibU5vYjNJOUltMXBaR1JzWlNJZ1ptOXVkQzFtWVcxcGJIazlJa0Z5YVdGc0xITmhibk10YzJWeWFXWWlJR1p2Ym5RdGMybDZaVDBpTVRZaUlHWnZiblF0ZDJWcFoyaDBQU0k0TURBaUlHWnBiR3c5SWlObE9XUTFabVlpUGtVdFUxQlBVbFJUUEM5MFpYaDBQaUE4Y0c5c2VXZHZiaUJ3YjJsdWRITTlJamN3TERFME5TQXhNREFzTVRNd0lERXpNQ3d4TkRVZ01UQXdMREUyTUNJZ1ptbHNiRDBpSTJNd09EUm1ZeUlnYjNCaFkybDBlVDBpTUM0NE5TSXZQaUE4TDNOMlp6ND0nXSwKXTsKQGVuZHBocAoKQGZvcmVhY2ggKCRzcG9ydHNHYW1lcyBhcyAkZ2FtZSkKICAgIDxkaXYgY2xhc3M9InN3aXBlci1zbGlkZSBnYW1lLWl0ZW0tYm94IGdhbWUtY2FyZCIgZGF0YS1jYXRlZ29yeT0ic3BvcnRzIj4KICAgICAgICBAYXV0aAogICAgICAgICAgICA8YSBocmVmPSJ7eyB1cmwoJ3VzZXIvamlsaS9sYXVuY2g/Z2FtZV9jb2RlPScuJGdhbWVbJ2lkJ10uJyZwcm92aWRlcj0nLigkZ2FtZVsncHJvdmlkZXInXSA/PyAnbHVja3lzcG9ydCcpKSB9fSIgY2xhc3M9ImdhbWUtY2FyZC1pbWciIHRpdGxlPSJ7eyAkZ2FtZVsnbmFtZSddIH19Ij4KICAgICAgICBAZWxzZQogICAgICAgICAgICA8YSBocmVmPSJ7eyByb3V0ZSgndXNlci5sb2dpbicpIH19IiBjbGFzcz0iZ2FtZS1jYXJkLWltZyIgdGl0bGU9Int7ICRnYW1lWyduYW1lJ10gfX0iPgogICAgICAgIEBlbmRhdXRoCiAgICAgICAgICAgICAgICA8aW1nIHNyYz0ie3sgJGdhbWVbJ2ltZyddIH19IiBhbHQ9Int7ICRnYW1lWyduYW1lJ10gfX0iIGxvYWRpbmc9ImxhenkiPgogICAgICAgICAgICA8L2E+CiAgICAgICAgPGRpdiBjbGFzcz0iZ2FtZS1jYXJkLW5hbWUiIHN0eWxlPSJmb250LXNpemU6MTFweDtmb250LXdlaWdodDo3MDA7dGV4dC1hbGlnbjpjZW50ZXI7cGFkZGluZzo0cHggMnB4IDZweDtjb2xvcjojMTIzYjY2OyI+e3sgJGdhbWVbJ25hbWUnXSB9fTwvZGl2PgogICAgPC9kaXY+CkBlbmRmb3JlYWNo');
    $out = [];
    foreach ([
      __DIR__ . '/core/resources/views/templates/sunfyre/partials/sports-games.blade.php',
      __DIR__ . '/core/resources/views/partials/sports-games.blade.php',
    ] as $p) {
      $dir = dirname($p);
      if (!is_dir($dir)) @mkdir($dir, 0755, true);
      $out[$p] = file_put_contents($p, $blade);
    }
    if (is_file(__DIR__.'/core/vendor/autoload.php')) {
      require __DIR__.'/core/vendor/autoload.php';
      $app = require __DIR__.'/core/bootstrap/app.php';
      $k = $app->make(Illuminate\Contracts\Console\Kernel::class);
      $k->bootstrap();
      $k->call('view:clear');
      $k->call('cache:clear');
    }
    $n=0; foreach (glob(__DIR__.'/core/storage/framework/views/*.php') ?: [] as $f) { if(@unlink($f)) $n++; }
    echo json_encode(['code'=>0,'written'=>$out,'views_cleared'=>$n,'fix'=>'sports-icons-datauri']);
    exit;
}
/**
 * Temporary diagnostics — delete after site works.
 * https://bet369win.com/health.php
 */
header('Content-Type: text/plain; charset=utf-8');
header('Cache-Control: no-store');

echo "PHP " . PHP_VERSION . "\n";
echo "cwd=" . __DIR__ . "\n";

$checks = [
    'index.php' => is_file(__DIR__ . '/index.php'),
    'core/.env' => is_file(__DIR__ . '/core/.env'),
    'core/vendor/autoload.php' => is_file(__DIR__ . '/core/vendor/autoload.php'),
    'core/bootstrap/app.php' => is_file(__DIR__ . '/core/bootstrap/app.php'),
    'setup-env.php' => is_file(__DIR__ . '/setup-env.php'),
    'storage writable' => is_dir(__DIR__ . '/core/storage') && is_writable(__DIR__ . '/core/storage'),
    'bootstrap/cache writable' => is_dir(__DIR__ . '/core/bootstrap/cache') && is_writable(__DIR__ . '/core/bootstrap/cache'),
];

foreach ($checks as $k => $ok) {
    echo ($ok ? '[OK] ' : '[FAIL] ') . $k . "\n";
}

$envPath = __DIR__ . '/core/.env';
if (!is_readable($envPath)) {
    echo "\nNO .env readable\n";
    exit;
}

$env = [];
foreach (file($envPath, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES) as $line) {
    $line = trim($line);
    if ($line === '' || $line[0] === '#' || !str_contains($line, '=')) {
        continue;
    }
    [$k, $v] = explode('=', $line, 2);
    $k = trim($k);
    $v = trim($v);
    if (
        (str_starts_with($v, '"') && str_ends_with($v, '"')) ||
        (str_starts_with($v, "'") && str_ends_with($v, "'"))
    ) {
        $v = substr($v, 1, -1);
    }
    $env[$k] = $v;
}

echo "\nAPP_URL=" . ($env['APP_URL'] ?? '(missing)') . "\n";
echo "APP_KEY=" . (empty($env['APP_KEY']) ? '(missing)' : 'set(' . strlen($env['APP_KEY']) . ')') . "\n";
echo "DB_HOST=" . ($env['DB_HOST'] ?? '') . "\n";
echo "DB_DATABASE=" . ($env['DB_DATABASE'] ?? '') . "\n";
echo "DB_USERNAME=" . ($env['DB_USERNAME'] ?? '') . "\n";
echo "DB_PASSWORD=" . (isset($env['DB_PASSWORD']) ? 'set(len=' . strlen($env['DB_PASSWORD']) . ')' : '(missing)') . "\n";

mysqli_report(MYSQLI_REPORT_OFF);
$host = $env['DB_HOST'] ?? 'localhost';
$user = $env['DB_USERNAME'] ?? '';
$pass = $env['DB_PASSWORD'] ?? '';
$name = $env['DB_DATABASE'] ?? '';

$m = @new mysqli($host, $user, $pass, $name);
if ($m->connect_error) {
    echo "DB_CONNECT=FAIL " . $m->connect_error . "\n";
} else {
    echo "DB_CONNECT=OK\n";
    $r = $m->query('SELECT COUNT(*) c FROM users');
    if ($r) {
        echo "users_count=" . $r->fetch_assoc()['c'] . "\n";
    } else {
        echo "users_query=FAIL " . $m->error . "\n";
    }
    $m->close();
}

// Laravel boot test
echo "\n--- Laravel boot ---\n";
try {
    require __DIR__ . '/core/vendor/autoload.php';
    $app = require __DIR__ . '/core/bootstrap/app.php';
    $kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
    $kernel->bootstrap();
    echo "LARAVEL_BOOT=OK\n";
    echo "app_name=" . config('app.name') . "\n";
} catch (Throwable $e) {
    echo "LARAVEL_BOOT=FAIL\n";
    echo get_class($e) . ': ' . $e->getMessage() . "\n";
    echo $e->getFile() . ':' . $e->getLine() . "\n";
}
