@php
    $cq9Games = [
        ["id" => "7057b9185aaee613216ff18352ad1c2f", "name" => "Hot Spin", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/19.png"],
        ["id" => "7148d1ecd2f6787e3d4cfae4580a7b86", "name" => "5 God beasts", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/117.png"],
        ["id" => "572ed9f08de5745603c052fd759989c5", "name" => "Jewel Luxury", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/103.png"],
        ["id" => "c069592afd5d6ffab7bf759a491a71cd", "name" => "Lucky Bats", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/10.png"],
        ["id" => "660de502d52d1f4566aeab989491686f", "name" => "Flying Cai Shen", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/113.png"],
        ["id" => "89c763b3761557eaa960d022cdd73921", "name" => "Lord Ganesha", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/195.png"],
        ["id" => "cee72070e3d6fee077cfcb9a050df57d", "name" => "Money Tree", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/208.png"],
        ["id" => "2df7d3f0fb6dc289a29d58067ab1c596", "name" => "RunningToro", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/86.png"],
        ["id" => "15e8bdff25079b4be98f84cdea37d1ed", "name" => "Greek Gods", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/171.png"],
        ["id" => "201cd3554cef14c33b4f4011a9506d8d", "name" => "Paradise", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/AB3.png"],
        ["id" => "bdbb2665530867b57a3e3a42103fe39a", "name" => "LuckyFishing", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/AT05.png"],
        ["id" => "cf4cfcd1f517360be7e3f5e35cb277ef", "name" => "Wheel Money", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/128.png"],
        ["id" => "421ca8d057205d7af4e8cfea22cc906b", "name" => "Mini Roulette", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/213.png"],
        ["id" => "73e303cf417c6bd211ef536507a35b82", "name" => "Rave Jump 2 M", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/121.png"],
        ["id" => "a7034f531232014969b8b613fccd0a47", "name" => "Red Phoenix", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/77.png"],
        ["id" => "708c6a3de19dd4d7674efea3ef2fe40f", "name" => "888", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/20.png"],
        ["id" => "69092d998124631d4a8925944bce67b5", "name" => "Golden Eggs", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/67.png"],
        ["id" => "97bf63574981264cb987c086f51c4664", "name" => "Hero Fishing", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/GO02.png"],
        ["id" => "2d44ee24e038513e1d8680d4dd534348", "name" => "Poseidon", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/80.png"],
        ["id" => "8a244973588309c9d06b3d2f23020e1e", "name" => "Treasure House", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/12.png"],
        ["id" => "461e0b9219d51eda0f6413b19153a1c6", "name" => "Ganesha Jr.", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/GB6.png"],
        ["id" => "521c3e444d06b25dc5ed6b6768200d44", "name" => "777", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/26.png"],
        ["id" => "44b775adacc090fd07ad6b24a6b55963", "name" => "Aladdin's lamp", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/177.png"],
        ["id" => "260d42bbe34ce7149c636e339100364b", "name" => "Gu Gu Gu 3", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/180.png"],
        ["id" => "a36b6a69ffa118773a5e828bcc74dcf8", "name" => "Cricket Fever", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/188.png"],
        ["id" => "e8a984c3aa5e951ef92b053b32ea7dd1", "name" => "Super5", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/16.png"],
        ["id" => "551c0c158cfcbe2d8c97960f70c7fec8", "name" => "Football Fever", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/GB9.png"],
        ["id" => "d859be0e915d1b72d6c3125fd3764eb0", "name" => "Fruity Carnival", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/102.png"],
        ["id" => "c66bcf7a826e781c96cd214c97ae2b67", "name" => "Invincible Elephant", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/124.png"],
        ["id" => "b1c4e04fc5de9e6fe06baf44a650d0e6", "name" => "Zuma Wild", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/122.png"],
        ["id" => "2075dc1439923a3210deba122fc0d631", "name" => "Funky Bingo", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/GB14.png"],
        ["id" => "9b8589482492af6a92397a889ce24784", "name" => "Dragon's Treasure", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/197.png"],
        ["id" => "5e4818e6c8946a3d71653e3d22a9a1c9", "name" => "Yuan Bao", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/23.png"],
        ["id" => "20ac774b757e927af3fd59a67e39254a", "name" => "Night City", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/229.png"],
        ["id" => "GB12", "name" => "Myeong-ryang", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/GB12.png"],
        ["id" => "133", "name" => "Good Fortune M", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/133.png"],
        ["id" => "144", "name" => "Diamond Treasure", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/144.png"],
        ["id" => "5007", "name" => "Da Fa Cai", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/5007.png"],
        ["id" => "46", "name" => "Wolf Moon", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/46.png"],
        ["id" => "AS01", "name" => "Boots Of Luck", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/AS01.png"],
        ["id" => "118", "name" => "SkrSkr", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/118.png"],
        ["id" => "Thor 2", "name" => "Thor 2", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/182.png"],
        ["id" => "196", "name" => "Tenfold Eggs", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/196.png"],
        ["id" => "116", "name" => "Wonderland", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/116.png"],
        ["id" => "5009", "name" => "Uproar in Heaven", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/5009.png"],
        ["id" => "64", "name" => "Zeus", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/64.png"],
        ["id" => "8", "name" => "So Sweet", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/8.png"],
        ["id" => "108", "name" => "Jump Higher Mobile", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/108.png"],
        ["id" => "138", "name" => "Move n' Jump", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/138.png"],
        ["id" => "44", "name" => "Fruit King II", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/44.png"],
        ["id" => "GB1", "name" => "3 2 1 Go!", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/GB1.png"],
        ["id" => "69", "name" => "Fa Cai Shen", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/69.png"],
        ["id" => "223", "name" => "Acrobatics", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/223.png"],
        ["id" => "2", "name" => "God Of Chess", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/2.png"],
        ["id" => "4", "name" => "Wild Tarzan", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/4.png"],
        ["id" => "194", "name" => "Fortune Dragon", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/194.png"],
        ["id" => "205", "name" => "DiscoNight", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/205.png"],
        ["id" => "125", "name" => "Zeus M", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/125.png"],
        ["id" => "207", "name" => "Thai HILO", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/207.png"],
        ["id" => "GO169", "name" => "Dragon Pachinko", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/GO169.png"],
        ["id" => "136", "name" => "Running Animals", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/136.png"],
        ["id" => "186", "name" => "Fire Queen 2", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/186.png"],
        ["id" => "200", "name" => "Alice Run", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/200.png"],
        ["id" => "38", "name" => "All Wilds", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/38.png"],
        ["id" => "GB16", "name" => "CHICAGOⅡ", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/GB16.png"],
        ["id" => "222", "name" => "Loy Krathong", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/222.png"],
        ["id" => "70", "name" => "Wanbao Dino", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/70.png"],
        ["id" => "GB3", "name" => "Coin Spinner", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/GB3.png"],
        ["id" => "AS18", "name" => "Wild Fudge", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/AS18.png"],
        ["id" => "230", "name" => "Baseball Fever", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/230.png"],
        ["id" => "243", "name" => "Mafia", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/243.png"],
        ["id" => "GB13", "name" => "Football Fever M", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/GB13.png"],
        ["id" => "142", "name" => "Hephaestus", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/142.png"],
        ["id" => "148", "name" => "Fortune Totem", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/148.png"],
        ["id" => "112", "name" => "Pyramid Raider", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/112.png"],
        ["id" => "129", "name" => "Gu Gu Gu 2 M", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/129.png"],
        ["id" => "147", "name" => "Flower Fortunes", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/147.png"],
        ["id" => "39", "name" => "Apsaras", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/39.png"],
        ["id" => "146", "name" => "Sky Lanterns", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/146.png"],
        ["id" => "227", "name" => "888 Cai Shen", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/227.png"],
        ["id" => "154", "name" => "Kronos", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/154.png"],
        ["id" => "1", "name" => "Fruit King", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/1.png"],
        ["id" => "242", "name" => "Treasure Pirate", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/242.png"],
        ["id" => "95", "name" => "Football Boots", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/95.png"],
        ["id" => "55", "name" => "Dragon Heart", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/55.png"],
        ["id" => "153", "name" => "Six Candy", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/153.png"],
        ["id" => "143", "name" => "Fa Cai Fu Wa", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/143.png"],
        ["id" => "51", "name" => "Ecstatic Circus", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/51.png"],
        ["id" => "57", "name" => "The Beast War", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/57.png"],
        ["id" => "76", "name" => "WonWonWon", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/76.png"],
        ["id" => "24", "name" => "Rave Jump2", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/24.png"],
        ["id" => "217", "name" => "Mahjong Fruit", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/217.png"],
        ["id" => "111", "name" => "Fly Out", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/111.png"],
        ["id" => "160", "name" => "Fa Cai Shen2", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/160.png"],
        ["id" => "50", "name" => "Good Fortune", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/50.png"],
        ["id" => "98", "name" => "All Star Team", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/98.png"],
        ["id" => "216", "name" => "Xoc Dia", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/216.png"],
        ["id" => "83", "name" => "Fire Queen", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/83.png"],
        ["id" => "GO01", "name" => "Dragon Ball Dozer", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/GO01.png"],
        ["id" => "58", "name" => "Gu Gu Gu 2", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/58.png"],
        ["id" => "221", "name" => "Detective Dee 2", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/221.png"],
        ["id" => "109", "name" => "Rave Jump Mobile", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/109.png"],
        ["id" => "225", "name" => "Mr. Miser", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/225.png"],
        ["id" => "201", "name" => "MuayThai", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/201.png"],
        ["id" => "219", "name" => "King Kong Shake", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/219.png"],
        ["id" => "211", "name" => "King of Atlantis", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/211.png"],
        ["id" => "152", "name" => "Double Fly", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/152.png"],
        ["id" => "89", "name" => "Thor", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/89.png"],
        ["id" => "78", "name" => "Apollo", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/78.png"],
        ["id" => "185", "name" => "Dragon Ball", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/185.png"],
        ["id" => "52", "name" => "Jump High", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/52.png"],
        ["id" => "214", "name" => "Ninja Raccoon", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/214.png"],
        ["id" => "21", "name" => "Big Wolf", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/21.png"],
        ["id" => "60", "name" => "Jungle Party", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/60.png"],
        ["id" => "AS04", "name" => "Fortune Spirits", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/AS04.png"],
        ["id" => "241", "name" => "The Chicken House", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/241.png"],
        ["id" => "204", "name" => "LuckyBoxes", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/204.png"],
        ["id" => "17", "name" => "Great Lion", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/17.png"],
        ["id" => "115", "name" => "Snow Queen", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/115.png"],
        ["id" => "105", "name" => "Jumping Mobile", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/105.png"],
        ["id" => "135", "name" => "Gu Gu Gu M", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/135.png"],
        ["id" => "184", "name" => "Six Gacha", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/184.png"],
        ["id" => "137", "name" => "Disco Night M", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/137.png"],
        ["id" => "140", "name" => "Fire Chibi 2", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/140.png"],
        ["id" => "179", "name" => "Jump High 2", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/179.png"],
        ["id" => "231", "name" => "Striker WILD", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/231.png"],
        ["id" => "5008", "name" => "Da Hong Zhong", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/5008.png"],
        ["id" => "49", "name" => "Lonely Planet", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/49.png"],
        ["id" => "161", "name" => "Hercules", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/161.png"],
        ["id" => "15", "name" => "GuGuGu", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/15.png"],
        ["id" => "226", "name" => "Lucky Tigers", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/226.png"],
        ["id" => "GB11", "name" => "Thai Fish Prawn Crab", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/GB11.png"],
        ["id" => "68", "name" => "Wukong & Peaches", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/68.png"],
        ["id" => "61", "name" => "Mr. Bean", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/61.png"],
        ["id" => "GB15", "name" => "Hero of the 3 Kingdoms - Cao Cao", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/GB15.png"],
        ["id" => "GB7", "name" => "Mummy's Treasure", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/GB7.png"],
        ["id" => "132", "name" => "Meow", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/132.png"],
        ["id" => "157", "name" => "5 Boxing", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/157.png"],
        ["id" => "228", "name" => "Mirror Mirror", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/228.png"],
        ["id" => "3", "name" => "Vampire Kiss", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/3.png"],
        ["id" => "131", "name" => "Fa Cai Shen M", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/131.png"],
        ["id" => "99", "name" => "Jump Higher", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/99.png"],
        ["id" => "96", "name" => "Football Baby", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/96.png"],
        ["id" => "72", "name" => "Happy Rich Year", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/72.png"],
        ["id" => "GB198", "name" => "Hanuman Bingo", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/GB198.png"],
        ["id" => "5", "name" => "Mr. Rich", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/5.png"],
        ["id" => "54", "name" => "Funny Alpaca", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/54.png"],
        ["id" => "31", "name" => "God of War", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/31.png"],
        ["id" => "GB8", "name" => "Dragon Koi", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/GB8.png"],
        ["id" => "AS03", "name" => "Dragon Hunters", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/AS03.png"],
        ["id" => "AS10", "name" => "Lucky 3", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/AS10.png"],
        ["id" => "81", "name" => "Treasure Island", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/81.png"],
        ["id" => "9", "name" => "Zhong Kui", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/9.png"],
        ["id" => "141", "name" => "Xmas", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/141.png"],
        ["id" => "130", "name" => "Gold Stealer", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/130.png"],
        ["id" => "218", "name" => "Dollar Bomb", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/218.png"],
        ["id" => "AS33", "name" => "Pig Of Luck", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/AS33.png"],
        ["id" => "AS08", "name" => "Golden Mayan", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/AS08.png"],
        ["id" => "59", "name" => "Summer Mood", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/59.png"],
        ["id" => "215", "name" => "Hot Pinatas", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/215.png"],
        ["id" => "212", "name" => "Burning Xi-You", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/212.png"],
        ["id" => "33", "name" => "Fire Chibi", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/33.png"],
        ["id" => "47", "name" => "Pharaoh's Gold", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/47.png"],
        ["id" => "35", "name" => "Crazy Nuozha", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/35.png"],
        ["id" => "27", "name" => "Magic World", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/27.png"],
        ["id" => "209", "name" => "The Cupids", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/209.png"],
        ["id" => "123", "name" => "Lucky Bats M", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/123.png"],
        ["id" => "104", "name" => "Chicky Parm Parm", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/104.png"],
        ["id" => "163", "name" => "Ne Zha Advent", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/163.png"],
        ["id" => "150", "name" => "Shou-Xin", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/150.png"],
        ["id" => "187", "name" => "Wing Chun", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/187.png"],
        ["id" => "AS09", "name" => "Hollywood Pets", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/AS09.png"],
        ["id" => "AS19", "name" => "Xmas Tales", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/AS19.png"],
        ["id" => "GB2", "name" => "Monster Hunter", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/GB2.png"],
        ["id" => "GB5", "name" => "Hot DJ", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/GB5.png"],
        ["id" => "7", "name" => "Rave Jump", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/7.png"],
        ["id" => "92", "name" => "World Cup Russia2018", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/92.png"],
        ["id" => "AS02", "name" => "Cirque de fous", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/AS02.png"],
        ["id" => "127", "name" => "God of War M", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/127.png"],
        ["id" => "139", "name" => "Fire Chibi M", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/139.png"],
        ["id" => "206", "name" => "Sweet POP", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/206.png"],
        ["id" => "203", "name" => "RaveHigh", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/203.png"],
        ["id" => "199", "name" => "Songkran Festival", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/199.png"],
        ["id" => "224", "name" => "K.O. Island", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/224.png"],
        ["id" => "220", "name" => "Floating Market", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/220.png"],
        ["id" => "34", "name" => "Gophers War", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/34.png"],
        ["id" => "36", "name" => "Pub Tycoon", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/36.png"],
        ["id" => "29", "name" => "WaterWorld", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/29.png"],
        ["id" => "32", "name" => "Detective Dee", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/32.png"],
        ["id" => "42", "name" => "Sherlock Holmes", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/42.png"],
        ["id" => "22", "name" => "Monkey Office Legend", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/22.png"],
        ["id" => "202", "name" => "OrientalBeauty", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/202.png"],
        ["id" => "210", "name" => "Oo Ga Cha Ka", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/210.png"],
        ["id" => "13", "name" => "Sakura Legend", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/13.png"],
        ["id" => "173", "name" => "6 Toros", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/173.png"],
        ["id" => "183", "name" => "Wolf Disco", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/183.png"],
        ["id" => "79", "name" => "Chameleon", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/79.png"],
        ["id" => "AS20", "name" => "Queen Of Dead", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/AS20.png"],
        ["id" => "GB10", "name" => "Seotda", "img" => "https://ossimg.diuacting.com/DiuWin/gamelogo/CQ9/GB10.png"],
    ];
@endphp

@foreach ($cq9Games as $game)
    <div class="swiper-slide game-item-box game-card" data-category="cq9">
        @auth
            <a href="{{ url('user/jili/launch?game_code='.$game['id'].'&provider=cq9') }}" class="game-card-img">
        @else
            <a href="{{ route('user.login') }}" class="game-card-img">
        @endauth
                <img src="{{ $game['img'] }}" alt="{{ $game['name'] }}">
            </a>
    </div>
@endforeach